export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const SET_USER = 'SET_USER';
export const USER_CREATION_MAIL = "USER_CREATION_MAIL";
export const USER_CREATION_USERNAME = "USER_CREATION_USERNAME";
export const USER_CREATION_PHOTO = "USER_CREATION_PHOTO";
export const USER_CREATION_PASSWORD = "USER_CREATION_PASSWORD";
export const CLEAR_USER_CREATION_DATA = "CLEAR_USER_CREATION_DATA";
